version: '3.8'
services:

  #Nginx Service
  server:
    image: nginx:1.17
    container_name: server
    depends_on:
      - app
      - db
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./config/nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - app-network

  #PHP Service
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAG: dev
    working_dir: /var/www
    volumes:
      - ./public:/var/www/html
      - ./config/php:/usr/local/etc/php/local.ini
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: gamehub
      MYSQL_USER: arxn
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_PASSWORD: arxn8767
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./database:/var/lib/mysql
      - ./config/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  #phpMyAdmin Service
  admin:
    image: phpmyadmin/phpmyadmin
    container_name: admin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3307
      PMA_ARBITRARY: 1
    restart: unless-stopped
    ports:
      - "3388:3388"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Docker Volumes
volumes:
  database: