version: '3.1'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: php-fpm.Dockerfile
    image: gamehub
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAG: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #MySQL Service
  db:
    # build:
    #   context: .
    #   dockerfile: mysql.Dockerfile
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    restart: always
    tty: true
    ports:
      - "5550:5550"
    environment:
      - MYSQL_DATABASE=master
      - MYSQL_USER=arxn
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_PASSWORD=arxn8767
    volumes:
      - dbdata:/var/lib/mysql
      # - ./config/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  #phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 5550
      PMA_ARBITRARY: 1
    restart: unless-stopped
    ports:
      - 3388:3388
    networks:
      - app-network

  #Nginx Service
  webserver:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    # image: nginx:alpine
    container_name: webserver
    depends_on:
      - app
      - db
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./config/nginx:/etc/nginx
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Docker Volumes
volumes:
  dbdata:
    driver: local